# Generated by Django 4.1.7 on 2024-09-27 00:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(db_index=True, max_length=200)),
                ('CONTACTO', models.CharField(blank=True, max_length=200, null=True)),
                ('TELEFONO', models.CharField(max_length=200)),
                ('CORREO', models.CharField(blank=True, max_length=200, null=True)),
                ('TIPO_PAGO', models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('CREDITO', 'CREDITO')], max_length=200)),
                ('OBSERVACIONES', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CALLE', models.CharField(max_length=200)),
                ('NUMERO', models.CharField(max_length=200)),
                ('COLONIA', models.CharField(blank=True, max_length=200, null=True)),
                ('CIUDAD', models.CharField(max_length=200)),
                ('MUNICIPIO', models.CharField(blank=True, max_length=200, null=True)),
                ('CP', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMAGEN', models.ImageField(blank=True, null=True, upload_to='imagenes/empleados')),
                ('ROLE', models.CharField(choices=[('GERENTE', 'GERENTE'), ('CAJERO', 'CAJERO'), ('REPARTIDOR', 'REPARTIDOR')], default='CAJERO', max_length=255)),
                ('CIUDAD_REGISTRO', models.CharField(choices=[('LAZARO', 'LAZARO'), ('URUAPAN', 'URUAPAN')], db_index=True, default='URUAPAN', max_length=15)),
                ('USUARIO', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=100)),
                ('CANTIDAD', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('PRECIO', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('IMAGEN', models.ImageField(blank=True, null=True, upload_to='imagenes/productos')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=100, unique=True)),
                ('REPARTIDOR_NOMBRE', models.CharField(max_length=200)),
                ('REPARTIDOR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='RutaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REPARTIDOR_NOMBRE', models.CharField(max_length=200)),
                ('DIA', models.CharField(choices=[('LUNES', 'LUNES'), ('MARTES', 'MARTES'), ('MIERCOLES', 'MIERCOLES'), ('JUEVES', 'JUEVES'), ('VIERNES', 'VIERNES'), ('SABADO', 'SABADO'), ('DOMINGO', 'DOMINGO')], max_length=100)),
                ('REPARTIDOR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.empleado')),
                ('RUTA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_dias', to='api.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VENDEDOR', models.CharField(max_length=100)),
                ('NOMBRE_CLIENTE', models.CharField(db_index=True, max_length=200)),
                ('FECHA', models.DateTimeField(auto_now=True)),
                ('MONTO', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('TIPO_VENTA', models.CharField(choices=[('MOSTRADOR', 'MOSTRADOR'), ('RUTA', 'RUTA')], max_length=100)),
                ('TIPO_PAGO', models.CharField(choices=[('CONTADO', 'CONTADO'), ('CREDITO', 'CREDITO'), ('CORTESIA', 'CORTESIA')], max_length=100)),
                ('STATUS', models.CharField(choices=[('REALIZADO', 'REALIZADO'), ('PENDIENTE', 'PENDIENTE'), ('CANCELADO', 'CANCELADO')], max_length=100)),
                ('OBSERVACIONES', models.CharField(blank=True, max_length=100)),
                ('DESCUENTO', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('CLIENTE', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='SalidaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ATIENDE', models.CharField(max_length=100)),
                ('RUTA_NOMBRE', models.CharField(blank=True, max_length=200)),
                ('FECHA', models.DateTimeField(auto_now=True)),
                ('REPARTIDOR_NOMBRE', models.CharField(max_length=200)),
                ('OBSERVACIONES', models.CharField(blank=True, max_length=200)),
                ('STATUS', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PROGRESO', 'PROGRESO'), ('REALIZADO', 'REALIZADO'), ('CANCELADO', 'CANCELADO')], max_length=100)),
                ('REPARTIDOR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.empleado')),
                ('RUTA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salida_rutas', to='api.rutadia')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE_PRODUCTO', models.CharField(max_length=200)),
                ('CANTIDAD_VENTA', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('PRECIO_VENTA', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('PRODUCTO', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.producto')),
                ('VENTA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_venta', to='api.venta')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoSalidaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCTO_NOMBRE', models.CharField(max_length=200)),
                ('CANTIDAD_RUTA', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('CANTIDAD_DISPONIBLE', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('STATUS', models.CharField(choices=[('CARGADO', 'CARGADO'), ('VENDIDO', 'VENDIDO')], max_length=100)),
                ('PRODUCTO_RUTA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
                ('SALIDA_RUTA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='api.salidaruta')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRECIO', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('CLIENTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_cliente', to='api.cliente')),
                ('PRODUCTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DevolucionSalidaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REPARTIDOR', models.CharField(max_length=200)),
                ('ATIENDE', models.CharField(max_length=200)),
                ('ADMINISTRADOR', models.CharField(blank=True, max_length=200)),
                ('PRODUCTO_NOMBRE', models.CharField(max_length=200)),
                ('CANTIDAD_DEVOLUCION', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('STATUS', models.CharField(choices=[('REALIZADO', 'REALIZADO'), ('PENDIENTE', 'PENDIENTE')], default='PENDIENTE', max_length=200)),
                ('OBSERVACIONES', models.CharField(blank=True, max_length=200)),
                ('FECHA', models.DateTimeField(auto_now=True)),
                ('PRODUCTO_DEVOLUCION', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.producto')),
                ('SALIDA_RUTA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salida_ruta_devoluciones', to='api.salidaruta')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteSalidaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLIENTE_NOMBRE', models.CharField(max_length=200)),
                ('STATUS', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('VISITADO', 'VISITADO')], max_length=100)),
                ('CLIENTE_RUTA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cliente')),
                ('SALIDA_RUTA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='api.salidaruta')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='DIRECCION',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.direccion'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='RUTAS',
            field=models.ManyToManyField(blank=True, related_name='clientes_ruta', to='api.rutadia'),
        ),
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAJERO', models.CharField(max_length=200)),
                ('BODEGA', models.CharField(max_length=200)),
                ('ADMINISTRADOR', models.CharField(blank=True, max_length=200)),
                ('PRODUCTO_NOMBRE', models.CharField(max_length=200)),
                ('CANTIDAD', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('TIPO_AJUSTE', models.CharField(choices=[('FALTANTE', 'FALTANTE'), ('SOBRANTE', 'SOBRANTE')], max_length=10)),
                ('STATUS', models.CharField(choices=[('REALIZADO', 'REALIZADO'), ('PENDIENTE', 'PENDIENTE')], default='PENDIENTE', max_length=200)),
                ('FECHA', models.DateTimeField(auto_now=True)),
                ('OBSERVACIONES', models.CharField(blank=True, max_length=200)),
                ('PRODUCTO', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.producto')),
            ],
        ),
    ]
