# Generated by Django 4.1.7 on 2024-01-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajusteinventario',
            name='FECHA',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
