# Generated by Django 4.1.7 on 2023-10-21 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_salidaruta_ruta_alter_salidaruta_ruta_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='DIRECCION',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.direccion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='TIPO_PAGO',
            field=models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('CREDITO', 'CREDITO')], default='', max_length=200),
            preserve_default=False,
        ),
    ]
