# Generated by Django 4.1.7 on 2024-01-23 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ajusteinventario_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devolucionsalidaruta',
            old_name='CATIDAD_DEVOLUCION',
            new_name='CANTIDAD_DEVOLUCION',
        ),
        migrations.AlterField(
            model_name='clientesalidaruta',
            name='STATUS',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('VISITADO', 'VISITADO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='devolucionsalidaruta',
            name='PRODUCTO_DEVOLUCION',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.producto'),
        ),
        migrations.AlterField(
            model_name='devolucionsalidaruta',
            name='STATUS',
            field=models.CharField(choices=[('REALIZADO', 'REALIZADO'), ('PENDIENTE', 'PENDIENTE')], default='PENDIENTE', max_length=200),
        ),
        migrations.AlterField(
            model_name='productosalidaruta',
            name='STATUS',
            field=models.CharField(choices=[('CARGADO', 'CARGADO'), ('VENDIDO', 'VENDIDO')], max_length=100),
        ),
    ]
