# Generated by Django 4.1.7 on 2023-10-21 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cliente_direccion_alter_cliente_tipo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='DIRECCION',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.direccion'),
        ),
    ]
