# Generated by Django 4.1.7 on 2024-09-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cliente_ciudad_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajusteinventario',
            name='CIUDAD_REGISTRO',
            field=models.CharField(choices=[('LAZARO', 'LAZARO'), ('URUAPAN', 'URUAPAN')], db_index=True, default='URUAPAN', max_length=15),
        ),
    ]
