# Generated by Django 4.1.7 on 2024-01-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_devolucionsalidaruta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='ROLE',
            field=models.CharField(choices=[('GERENTE', 'GERENTE'), ('CAJERO', 'CAJERO'), ('REPARTIDOR', 'REPARTIDOR')], default='CAJERO', max_length=255),
        ),
    ]
