# Generated by Django 4.1.7 on 2023-12-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cliente_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajusteinventario',
            name='ADMINISTRADOR',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='NOMBRE',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
