# Generated by Django 4.1.7 on 2024-01-25 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_empleado_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucionsalidaruta',
            name='CANTIDAD_DEVOLUCION',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productosalidaruta',
            name='CANTIDAD_DISPONIBLE',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productosalidaruta',
            name='CANTIDAD_RUTA',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
