# Generated by Django 4.1.7 on 2023-12-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ajusteinventario_administrador_alter_cliente_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='NOMBRE_CLIENTE',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
