# Generated by Django 4.1.7 on 2024-11-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_salidaruta_ciudad_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='FOLIO',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
