# Generated by Django 4.1.7 on 2025-01-15 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_venta_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='FECHA',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
