# Generated by Django 4.1.7 on 2025-01-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_venta_fecha'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(fields=('FOLIO', 'CIUDAD_REGISTRO'), name='unique_folio_ciudad'),
        ),
    ]
