# Generated by Django 4.1.7 on 2025-01-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_venta_unique_folio_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='FECHA',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
