# Generated by Django 4.1.7 on 2025-01-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_empleado_ciudad_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='CIUDAD_REGISTRO',
            field=models.CharField(choices=[('LAZARO', 'LAZARO'), ('URUAPAN', 'URUAPAN')], db_index=True, default='URUAPAN', max_length=15),
        ),
    ]
