# Generated by Django 4.1.7 on 2025-11-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_productoventa_precio_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='FOLIO',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
