# Generated by Django 4.1.7 on 2025-11-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_venta_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidaruta',
            name='FOLIO',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='salidaruta',
            constraint=models.UniqueConstraint(fields=('FOLIO', 'CIUDAD_REGISTRO'), name='unique_folio_ciudad_salida_ruta'),
        ),
    ]
