# Generated by Django 4.1.7 on 2025-11-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_salidaruta_folio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaruta',
            name='FOLIO',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
