# Generated by Django 4.1.7 on 2025-11-03 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_salidaruta_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaruta',
            name='FOLIO',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
