# Generated by Django 4.1.7 on 2023-09-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_devolucionsalidaruta_catidad_devolucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajusteinventario',
            name='OBSERVACIONES',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ajusteinventario',
            name='STATUS',
            field=models.CharField(choices=[('REALIZADO', 'REALIZADO'), ('PENDIENTE', 'PENDIENTE')], default='PENDIENTE', max_length=200),
        ),
        migrations.AddField(
            model_name='devolucionsalidaruta',
            name='OBSERVACIONES',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
